{"version":1,"defects":{"Warning":6,"Tests\\Unit\\RouterTest::it_registers_a_route":3,"Tests\\Unit\\RouterTest::test_it_registers_a_route":4,"Tests\\Unit\\RouterTest::it_registers_a_post_route":3,"Tests\\Unit\\RouterTest::there_is_no_routes_when_router_is_created":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":3,"Error":4,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":3},"times":{"Warning":0.008,"Tests\\Unit\\RouterTest::it_registers_a_route":0.009,"Tests\\Unit\\RouterTest::test_it_registers_a_route":0.013,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::testit_registers_a_post_route":0,"Tests\\Unit\\RouterTest::there_is_no_routes_when_router_is_created":0.002,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.003,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Error":0.003,"Tests\\Unit\\RouterTest::it_resolves_a_route_from_callable":0,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":0.028,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":0.003}}